language: python

cache:
  - pip
  - ccache

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.6"


install:
  - pip install -U pip wheel
  - pip install pytest pytest-pythonpath hacking mock
  - pip install autopep8
  # unable to install pytorch as https://github.com/pytorch/pytorch/issues/4178
  # - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl; fi
  # - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl; fi
  # - cd tools && make warp-ctc && cd -
  - grep -v cupy tools/requirements.txt | pip install -r /dev/stdin
  - cd tools && make kaldi-io-for-python && cd -


script:
  # TODO test coding style?
  # - flake8
  # - autopep8 -r . --global-config .pep8 --diff | tee check_autopep8
  # - test ! -s check_autopep8
  - export PYTHONPATH=`pwd`/src/nets:`pwd`/src/utils
  - pytest test

sudo: false

addons:
  apt:
    packages:
      - cmake
      - python-dev
      - python3-dev
