model: contextual_asr_espnet

# network architecture
# encoder related
encoder: conformer
encoder_conf:
    output_size: 256    # dimension of attention
    attention_heads: 4
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d # encoder architecture type
    normalize_before: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    macaron_style: true
    use_cnn_module: true
    cnn_module_kernel: 31

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.
    src_attention_dropout_rate: 0.

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false

# minibatch related
batch_type: numel
batch_bins: 25000000

# optimization related
accum_grad: 1
grad_clip: 5
max_epoch: 20
val_scheduler_criterion:
    - valid
    - acc
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
   lr: 0.0005
#    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 35000

num_workers: 4      # num of workers of data loader
use_amp: true      # automatic mixed precision
unused_parameters: false    # set as true if some params are unused in DDP

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10

# contextual information settings
contextual: rareword
contextual_conf:
    contextual_type: rareword
    blist_path: ./local/contextual/rarewords/rareword_f1024_train.txt
    blist_occurrence_path: ./local/contextual/rarewords/rareword_f1024_train_occurrence.txt
    blist_max: 200
    blist_drop_out: 0.0
    structure_type: null
    # structure_type: trie
    sampling_method: null

# contextualizer settings
contextualizer: contextual_adapter_encoder
contextualizer_conf:
    contextualizer_type: contextual_adapter_encoder
    context_embed_size: 256
    context_hidden_size: 256
    model_hidden_size: 256
    input_hidden_size: 256
    proj_hidden_size: 256
    attndim: 256
    temperature: 10
    drop_out: 0.0
    warmup_epoch: 0
    contextualizer_weight: 0.5
    contextualizer_losses:
        loss_contextualizer_ga_ctc: 0.5
        loss_contextualizer_ga_reweight_lp: 0.5

# adapter style training
freeze_param: ["encoder", "decoder", "contextualizer.encoder.embed", "contextualizer.encoder.pad_embed"]