model: contextual_asr_espnet

batch_type: numel
batch_bins: 1250000
# batch_bins: 2500000
accum_grad: 16
max_epoch: 15
patience: none
init: none
num_att_plot: 0

val_scheduler_criterion:
    - valid
    - loss
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10

model_conf:
    ctc_weight: 0.0
    report_cer: False
    report_wer: False

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31

decoder: transducer
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 512
    dropout: 0.1
    dropout_embed: 0.2

joint_net_conf:
    joint_space_size: 640
    joint_type: biasing

optim: adam
optim_conf:
    lr: 0.0015
    # weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

frontend_conf:
  n_fft: 512
  hop_length: 160

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

# contextual information settings
contextual: rareword
contextual_conf:
    contextual_type: rareword
    blist_path: ./local/contextual/rarewords/rareword_f1000_train.txt
    blist_max: 200
    blist_drop_out: 0.0
    structure_type: null
    sampling_method: null

# contextualizer settings
contextualizer: contextual_adapter_encoder
contextualizer_conf:
    contextualizer_type: contextual_adapter_encoder
    context_embed_size: 512
    context_hidden_size: 512
    model_hidden_size: 512
    input_hidden_size: 512
    proj_hidden_size: 640
    attndim: 512
    temperature: 10
    drop_out: 0.0
    warmup_epoch: 0
    contextualizer_weight: 0.5
    contextualizer_losses:
        loss_contextualizer_ga_ctc: 1

# adapter style training
freeze_param: ["encoder", "decoder", "contextualizer.encoder.embed", "contextualizer.encoder.pad_embed"]