# Trained with A40 (48 GB) x 4 GPUs.
model: contextual_asr_espnet

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

decoder: transducer
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 512
    dropout: 0.1
    dropout_embed: 0.2

joint_net_conf:
    joint_space_size: 640

model_conf:
    ctc_weight: 0.0
    report_cer: False
    report_wer: False

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

seed: 2022
num_workers: 8
batch_type: numel
# batch_bins: 8000000
batch_bins: 2000000
# batch_bins: 1000000
accum_grad: 32
max_epoch: 150
patience: none
init: none
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10
use_amp: false

optim: adam
optim_conf:
    lr: 0.002

scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5

# contextual information settings
contextual: rareword
contextual_conf:
    contextual_type: rareword
    blist_path: ./local/contextual/rareword_f15.txt
    blist_max: 500
    blist_droup_out: 0.0
    warmup_epoch: 0
    structure_type: null
    # structure_type: trie
    sampling_method: null

# contextualizer settings
contextualizer: contextual_adapter_decoder
contextualizer_conf:
    contextualizer_type: contextual_adapter_decoder
    context_embed_size: 512
    context_hidden_size: 512
    model_hidden_size: 512
    attndim: 512
    proj_hidden_size: 512
    droup_out: 0.1

# adapter style training
freeze_param: ["encoder", "decoder", "joint_network"]