model: contextual_asr_espnet

encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 1024
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

seed: 2022
log_interval: 400
num_att_plot: 0
num_workers: 4
sort_in_batch: descending       # how to sort data in making batch
sort_batch: descending          # how to sort created batches
batch_type: numel
# batch_bins: 16000000
batch_bins: 8000000
# accum_grad: 4
accum_grad: 2
max_epoch: 70
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

use_amp: true
cudnn_deterministic: false
cudnn_benchmark: false

optim: adam
grad_clip: 1.0
optim_conf:
    lr: 0.002
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5

# contextual information settings
contextual: rareword
contextual_conf:
    contextual_type: rareword
    blist_path: ./local/contextual/rarewords/rareword_f15.txt
    blist_xphone_path: ./local/contextual/ssl_features/rareword_f15.xphone.seq.pt
    blist_max: 200
    blist_drop_out: 0.0
    structure_type: null
    # structure_type: trie
    sampling_method: null

# contextualizer settings
contextualizer: contextual_xphone_adapter_encoder
contextualizer_conf:
    contextualizer_type: contextual_xphone_adapter_encoder
    context_embed_size: 256
    context_hidden_size: 256
    model_hidden_size: 256
    attndim: 256
    proj_hidden_size: 256
    atten_temperature: 0.05
    drop_out: 0.0
    warmup_epoch: 0
    contextualizer_weight: 0.5
    contextualizer_losses:
        loss_contextualizer_ga_ctc: 1

# adapter style training
freeze_param: ["encoder", "decoder", "contextualizer.encoder.embed", "contextualizer.encoder.pad_embed"]